/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JJ' at '6/11/17 10:37 PM' with Gradle 2.6
 *
 * @author JJ, @date 6/11/17 10:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
